# Generated by Django 5.0.6 on 2024-09-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
