# Generated by Django 5.0.6 on 2024-09-14 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_youtubevideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('NeotericAI', 'NeotericAI'), ('ASI Inauguration', 'ASI Inauguration'), ('RIT Promo', 'RIT Promo'), ('FDP', 'FDP'), ('Program', 'Program'), ('Webinar', 'Webinar'), ('Testimonials', 'Testimonials'), ('Subject Lecture', 'Subject Lecture'), ('Data Structures', 'Data Structures'), ('RIT-AD & Histos Conf.', 'RIT-AD & Histos Conf.')], max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
